/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.AdminRole;
import backend.LibrarianUserDatabase;
import backend.Database;
import javax.swing.JFrame;

/**
 *
 * @author amrka
 */
public class Admin_Role extends javax.swing.JFrame implements Node {
    backend.AdminRole admin = new backend.AdminRole();
    Node parent;
    public Admin_Role() {
        initComponents();
    }

    @Override
    public Node getParentNode() {
        return parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
    /**
     * Creates new form AdminRole
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewLibrarian = new javax.swing.JButton();
        RemoveLibrarian = new javax.swing.JButton();
        AddLibrarian = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Admin Role");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ViewLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        ViewLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ViewLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        ViewLibrarian.setText("View Librarians");
        ViewLibrarian.setOpaque(true);
        ViewLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewLibrarianActionPerformed(evt);
            }
        });

        RemoveLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        RemoveLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RemoveLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        RemoveLibrarian.setText("Remove Librarian");
        RemoveLibrarian.setOpaque(true);
        RemoveLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveLibrarianActionPerformed(evt);
            }
        });

        AddLibrarian.setBackground(new java.awt.Color(0, 0, 0));
        AddLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddLibrarian.setForeground(new java.awt.Color(255, 255, 255));
        AddLibrarian.setText("Add Librarian");
        AddLibrarian.setOpaque(true);
        AddLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLibrarianActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setOpaque(true);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewLibrarian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(AddLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(AddLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLibrarianActionPerformed
        // TODO add your handling code here:
        AddLibrarian lib = new AddLibrarian(admin);
        lib.setParentNode(this);
        this.setVisible(false);
        lib.setVisible(true);
    }//GEN-LAST:event_AddLibrarianActionPerformed

    private void RemoveLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveLibrarianActionPerformed
        // TODO add your handling code here:
        RemoveLibrarian lib = new RemoveLibrarian(admin);
         lib.setParentNode(this);
        this.setVisible(false);
        lib.setVisible(true);
    }//GEN-LAST:event_RemoveLibrarianActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        admin.logout();
        this.setVisible(false);
        ((JFrame) this.getParentNode().getParentNode()).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void ViewLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLibrarianActionPerformed
        // TODO add your handling code here:
        ViewLibrarians lib = new ViewLibrarians(admin);
        lib.setParentNode(this);
        this.setVisible(false);
        lib.setVisible(true);
    }//GEN-LAST:event_ViewLibrarianActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLibrarian;
    private javax.swing.JButton Logout;
    private javax.swing.JButton RemoveLibrarian;
    private javax.swing.JButton ViewLibrarian;
    // End of variables declaration//GEN-END:variables
}
