/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.JFrame;

/**
 *
 * @author Blu-Ray
 */
public class LibrarianRole extends javax.swing.JFrame implements Node{
    

    /**
     * Creates new form LibrarianRole
     */
    Node parent;
    backend.LibrarianRole Librarian=new backend.LibrarianRole();
    public LibrarianRole() {
        initComponents();
    }
     
     @Override 
    public Node getParentNode(){
        return parent;
    }
    @Override
   public void setParentNode(Node node){
        this.parent = node;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddBook = new javax.swing.JButton();
        ViewBorrowedBooks = new javax.swing.JButton();
        ReturnBook = new javax.swing.JButton();
        ViewBooks = new javax.swing.JButton();
        BorrowBooks = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Librarian Role");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        AddBook.setBackground(new java.awt.Color(0, 0, 0));
        AddBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddBook.setForeground(new java.awt.Color(255, 255, 255));
        AddBook.setText("Add Book");
        AddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookActionPerformed(evt);
            }
        });

        ViewBorrowedBooks.setBackground(new java.awt.Color(0, 0, 0));
        ViewBorrowedBooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewBorrowedBooks.setForeground(new java.awt.Color(255, 255, 255));
        ViewBorrowedBooks.setText("View Borrowed Books");
        ViewBorrowedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBorrowedBooksActionPerformed(evt);
            }
        });

        ReturnBook.setBackground(new java.awt.Color(0, 0, 0));
        ReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ReturnBook.setForeground(new java.awt.Color(255, 255, 255));
        ReturnBook.setText("Return Book");
        ReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBookActionPerformed(evt);
            }
        });

        ViewBooks.setBackground(new java.awt.Color(0, 0, 0));
        ViewBooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ViewBooks.setForeground(new java.awt.Color(255, 255, 255));
        ViewBooks.setText("View Books");
        ViewBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksActionPerformed(evt);
            }
        });

        BorrowBooks.setBackground(new java.awt.Color(0, 0, 0));
        BorrowBooks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BorrowBooks.setForeground(new java.awt.Color(255, 255, 255));
        BorrowBooks.setText("Borrow Books");
        BorrowBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowBooksActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBorrowedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorrowBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(AddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(ViewBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(BorrowBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ViewBorrowedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksActionPerformed
        // TODO add your handling code here:
        ViewBooks book =new ViewBooks(Librarian);
        book.setParentNode(this);
        this.setVisible(false);
        book.setVisible(true);
    }//GEN-LAST:event_ViewBooksActionPerformed

    private void ReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBookActionPerformed
        // TODO add your handling code here:
        ReturnBook book =new ReturnBook(Librarian);
        book.setParentNode(this);
        this.setVisible(false);
        book.setVisible(true); 
    }//GEN-LAST:event_ReturnBookActionPerformed

    private void AddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookActionPerformed
        // TODO add your handling code here:
        AddBook book =new AddBook(Librarian);
        book.setParentNode(this);
        this.setVisible(false);
        book.setVisible(true);
        
    }//GEN-LAST:event_AddBookActionPerformed

    private void BorrowBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowBooksActionPerformed
        // TODO add your handling code here:
        BorrowBook book =new BorrowBook(Librarian);
        book.setParentNode(this);
        this.setVisible(false);
        book.setVisible(true);
        
    }//GEN-LAST:event_BorrowBooksActionPerformed

    private void ViewBorrowedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBorrowedBooksActionPerformed
        // TODO add your handling code here:
        ViewBorrowedBooks book =new ViewBorrowedBooks(Librarian);
        book.setParentNode(this);
        this.setVisible(false);
        book.setVisible(true);  
    }//GEN-LAST:event_ViewBorrowedBooksActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Librarian.logout();
        this.setVisible(false);
        ((JFrame) this.getParentNode().getParentNode()).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBook;
    private javax.swing.JButton BorrowBooks;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ReturnBook;
    private javax.swing.JButton ViewBooks;
    private javax.swing.JButton ViewBorrowedBooks;
    // End of variables declaration//GEN-END:variables
}
