/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.AdminRole;
import backend.LibrarianUser;   
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed
 */
public class RemoveLibrarian extends javax.swing.JFrame implements Node{

    Node parent;
    backend.AdminRole admin;
    @Override
    public Node getParentNode()
    {
        return parent;
    }
    
    @Override
    public void setParentNode(Node node){
        this.parent = node;
    }
    /**
     * Creates new form RemoveLibrarian
     */
    public RemoveLibrarian(backend.AdminRole admin) {
        initComponents();
        this.admin=admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LibrarianID = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IDLibrarian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Remove Librarian");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LibrarianID.setBackground(java.awt.Color.green);
        LibrarianID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LibrarianID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LibrarianID.setText("Librarian Id");
        LibrarianID.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        IDLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibrarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LibrarianID, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LibrarianID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDLibrarian)
                    .addComponent(jButton1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibrarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLibrarianActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String LibrarianId = IDLibrarian.getText();
          boolean check=false;
         LibrarianUser[]x= admin.getListOfLibrarians();
          for (int i=0; i <x.length;i++)
          {
              if(x[i].getSearchKey().equals(LibrarianId))
             {  
                check=true;
                admin.removeLibrarian(LibrarianId);
                JOptionPane.showMessageDialog(null, "The librarian with id="+LibrarianId+" has been deleted!");
             }
          }
          if(check ==false)
               JOptionPane.showMessageDialog(null, "The librarian with id="+LibrarianId+" doesn't exist!");
        IDLibrarian.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame) this.getParentNode()).setVisible(true);
       
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLibrarian;
    private javax.swing.JLabel LibrarianID;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
